SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python" LIMIT 1) > 0
OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "C#" LIMIT 1) > 0
ORDER BY D.ID ASC;