# 음식 종류별로 즐겨찾기 수가 가장 많은 식당의 음식 종류
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FAVORITES, FOOD_TYPE) IN (SELECT MAX(FAVORITES), FOOD_TYPE
                  FROM REST_INFO
                  GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;